"""Small shell wrappers so every tool has its own command name.

SBGrid gives each program a short command of its own. These wrappers do the
same for structbio: `rfdiffusion monomer 150 my_designs` is nothing more than
`structbio rfdiffusion monomer 150 my_designs`.
"""

from __future__ import annotations

import os
import shlex
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

from structbio.tools import get_backends


MARKER = "# Generated by structbio."

# structbio gets a wrapper of its own too. Without one, `structbio` resolves to
# whichever virtual environment happens to be active, which silently runs an
# older checkout; the wrappers always name their interpreter outright.
SELF_NAME = "structbio"

SELF_TEMPLATE = """#!/usr/bin/env bash
{marker} Regenerate with: structbio install-wrappers
# Runs this exact structbio installation, whatever environment is active.
set -euo pipefail

launcher=({launch})
resolved=$(command -v "${{launcher[0]}}" 2>/dev/null || true)
if [ -z "$resolved" ]; then
  echo "structbio: cannot find structbio at '${{launcher[0]}}'." >&2
  echo "Re-create the environment and run structbio install-wrappers again." >&2
  exit 127
fi
self=$(cd "$(dirname "$0")" && pwd)/$(basename "$0")
if [ "$resolved" = "$self" ]; then
  echo "structbio: this wrapper resolves to itself, which would loop forever." >&2
  echo "Run 'structbio install-wrappers' from the environment where structbio" >&2
  echo "is installed, so the wrapper names that interpreter outright." >&2
  exit 127
fi
exec "${{launcher[@]}}" "$@"
"""

WRAPPER_TEMPLATE = """#!/usr/bin/env bash
{marker} Regenerate with: structbio install-wrappers
# `{tool} ARGUMENTS` is exactly `structbio {tool} ARGUMENTS`.
set -euo pipefail

launcher=({launch})
if ! command -v "${{launcher[0]}}" >/dev/null 2>&1; then
  echo "{tool}: cannot find structbio at '${{launcher[0]}}'." >&2
  echo "Activate the environment where structbio is installed, then run" >&2
  echo "structbio install-wrappers again." >&2
  exit 127
fi
if [ "$#" -eq 0 ]; then
  exec "${{launcher[@]}}" {tool} --help
fi
exec "${{launcher[@]}}" {tool} "$@"
"""

DEFAULT_WRAPPER_DIR = Path("~/.local/bin")


def render_wrapper(tool: str, launch: str = "structbio") -> str:
    """Render the wrapper for one tool, or for structbio itself."""

    template = SELF_TEMPLATE if tool == SELF_NAME else WRAPPER_TEMPLATE
    return template.format(marker=MARKER, tool=tool, launch=launch)


def default_launch() -> str:
    """Find the most durable way to call this installation of structbio."""

    argv_zero = Path(sys.argv[0]) if sys.argv and sys.argv[0] else None
    if argv_zero and argv_zero.name == "structbio" and argv_zero.is_absolute():
        return shlex.quote(str(argv_zero))
    found = shutil.which("structbio")
    if found:
        return shlex.quote(found)
    return f"{shlex.quote(sys.executable)} -m structbio"


def wrapper_tools() -> list[str]:
    return [SELF_NAME, *sorted(get_backends())]


def install_wrappers(
    directory: Path, *, launch: str | None = None, force: bool = False
) -> list[tuple[Path, str]]:
    """Write one wrapper per backend, never silently replacing another program."""

    directory = directory.expanduser()
    directory.mkdir(parents=True, exist_ok=True)
    launch = launch or default_launch()
    results: list[tuple[Path, str]] = []
    for tool in wrapper_tools():
        path = directory / tool
        content = render_wrapper(tool, launch)
        if path.exists():
            existing = _read(path)
            if existing == content:
                results.append((path, "unchanged"))
                continue
            if MARKER not in existing and not force:
                results.append((path, "skipped: not a structbio wrapper"))
                continue
            path.write_text(content, encoding="utf-8")
            path.chmod(0o755)
            results.append((path, "updated"))
            continue
        path.write_text(content, encoding="utf-8")
        path.chmod(0o755)
        results.append((path, "created"))
    return results


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return ""


# ---------------------------------------------------------------------------
# Making the commands findable
# ---------------------------------------------------------------------------

PATH_MARKER = "# Added by structbio setup: the short tool commands live here."


@dataclass(frozen=True)
class PathResult:
    """What was needed, and done, to put the tool commands on PATH."""

    state: str
    bin_dir: Path
    line: str
    profile: Path | None = None

    @property
    def ready(self) -> bool:
        """True when this shell can already find the commands."""

        return self.state == "on PATH"

    @property
    def needs_reload(self) -> bool:
        """True when a profile is correct but this shell has not read it yet."""

        return self.state in ("added", "already in profile")


def path_line(bin_dir: Path) -> str:
    return f'export PATH="{bin_dir.expanduser().resolve()}:$PATH"'


def on_path(bin_dir: Path) -> bool:
    resolved = str(bin_dir.expanduser().resolve())
    entries = os.environ.get("PATH", "").split(os.pathsep)
    return any(entry and str(Path(entry).expanduser()) == resolved for entry in entries)


def profile_candidates(shell: str | None = None) -> list[Path]:
    """Shell start-up files to try, most specific first.

    Both login and interactive files are listed, because which one a terminal
    reads depends on how it was opened. Writing to the first writable one is
    enough for a new terminal in every arrangement seen in the lab.
    """

    name = Path(shell or os.environ.get("SHELL", "")).name
    home = Path.home()
    if name == "zsh":
        return [home / ".zshrc", home / ".zprofile", home / ".profile"]
    if name == "fish":
        return [home / ".config/fish/config.fish"]
    return [home / ".bashrc", home / ".bash_profile", home / ".profile"]


def _writable(path: Path) -> bool:
    """True when this user can append to that file, or create it."""

    if path.exists():
        return os.access(path, os.W_OK)
    return path.parent.exists() and os.access(path.parent, os.W_OK)


def writable_profile(shell: str | None = None) -> Path | None:
    """The first start-up file this user may edit, if there is one.

    A workstation shared through a managed image often has a root-owned
    `~/.zshrc`, which is why the first candidate is not simply assumed.
    """

    for candidate in profile_candidates(shell):
        if _writable(candidate):
            return candidate
    return None


def ensure_on_path(bin_dir: Path, *, shell: str | None = None) -> PathResult:
    """Put the wrapper directory on PATH for future shells, idempotently."""

    bin_dir = bin_dir.expanduser()
    line = path_line(bin_dir)
    if on_path(bin_dir):
        return PathResult("on PATH", bin_dir, line)
    profile = writable_profile(shell)
    if profile is None:
        return PathResult("no writable profile", bin_dir, line)
    existing = _read(profile) if profile.exists() else ""
    if line in existing:
        return PathResult("already in profile", bin_dir, line, profile)
    block = f"\n{PATH_MARKER}\n{line}\n"
    try:
        with profile.open("a", encoding="utf-8") as handle:
            handle.write(block if existing.endswith("\n") or not existing else f"\n{block}")
    except OSError:
        return PathResult("no writable profile", bin_dir, line)
    return PathResult("added", bin_dir, line, profile)
