"""Small shell wrappers so every tool has its own command name.

SBGrid gives each program a short command of its own. These wrappers do the
same for structbio: `rfdiffusion monomer 150 my_designs` is nothing more than
`structbio rfdiffusion monomer 150 my_designs`.
"""

from __future__ import annotations

import shlex
import shutil
import sys
from pathlib import Path

from structbio.tools import get_backends


MARKER = "# Generated by structbio."

# structbio gets a wrapper of its own too. Without one, `structbio` resolves to
# whichever virtual environment happens to be active, which silently runs an
# older checkout; the wrappers always name their interpreter outright.
SELF_NAME = "structbio"

SELF_TEMPLATE = """#!/usr/bin/env bash
{marker} Regenerate with: structbio install-wrappers
# Runs this exact structbio installation, whatever environment is active.
set -euo pipefail

launcher=({launch})
resolved=$(command -v "${{launcher[0]}}" 2>/dev/null || true)
if [ -z "$resolved" ]; then
  echo "structbio: cannot find structbio at '${{launcher[0]}}'." >&2
  echo "Re-create the environment and run structbio install-wrappers again." >&2
  exit 127
fi
self=$(cd "$(dirname "$0")" && pwd)/$(basename "$0")
if [ "$resolved" = "$self" ]; then
  echo "structbio: this wrapper resolves to itself, which would loop forever." >&2
  echo "Run 'structbio install-wrappers' from the environment where structbio" >&2
  echo "is installed, so the wrapper names that interpreter outright." >&2
  exit 127
fi
exec "${{launcher[@]}}" "$@"
"""

WRAPPER_TEMPLATE = """#!/usr/bin/env bash
{marker} Regenerate with: structbio install-wrappers
# `{tool} ARGUMENTS` is exactly `structbio {tool} ARGUMENTS`.
set -euo pipefail

launcher=({launch})
if ! command -v "${{launcher[0]}}" >/dev/null 2>&1; then
  echo "{tool}: cannot find structbio at '${{launcher[0]}}'." >&2
  echo "Activate the environment where structbio is installed, then run" >&2
  echo "structbio install-wrappers again." >&2
  exit 127
fi
if [ "$#" -eq 0 ]; then
  exec "${{launcher[@]}}" {tool} --help
fi
exec "${{launcher[@]}}" {tool} "$@"
"""

DEFAULT_WRAPPER_DIR = Path("~/.local/bin")


def render_wrapper(tool: str, launch: str = "structbio") -> str:
    """Render the wrapper for one tool, or for structbio itself."""

    template = SELF_TEMPLATE if tool == SELF_NAME else WRAPPER_TEMPLATE
    return template.format(marker=MARKER, tool=tool, launch=launch)


def default_launch() -> str:
    """Find the most durable way to call this installation of structbio."""

    argv_zero = Path(sys.argv[0]) if sys.argv and sys.argv[0] else None
    if argv_zero and argv_zero.name == "structbio" and argv_zero.is_absolute():
        return shlex.quote(str(argv_zero))
    found = shutil.which("structbio")
    if found:
        return shlex.quote(found)
    return f"{shlex.quote(sys.executable)} -m structbio"


def wrapper_tools() -> list[str]:
    return [SELF_NAME, *sorted(get_backends())]


def install_wrappers(
    directory: Path, *, launch: str | None = None, force: bool = False
) -> list[tuple[Path, str]]:
    """Write one wrapper per backend, never silently replacing another program."""

    directory = directory.expanduser()
    directory.mkdir(parents=True, exist_ok=True)
    launch = launch or default_launch()
    results: list[tuple[Path, str]] = []
    for tool in wrapper_tools():
        path = directory / tool
        content = render_wrapper(tool, launch)
        if path.exists():
            existing = _read(path)
            if existing == content:
                results.append((path, "unchanged"))
                continue
            if MARKER not in existing and not force:
                results.append((path, "skipped: not a structbio wrapper"))
                continue
            path.write_text(content, encoding="utf-8")
            path.chmod(0o755)
            results.append((path, "updated"))
            continue
        path.write_text(content, encoding="utf-8")
        path.chmod(0o755)
        results.append((path, "created"))
    return results


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return ""
